In [1]:
import numpy as np
def simplex(matriz_A, vetor_b, vetor_c):
    linhas, colunas = matriz_A.shape
    tabela = np.zeros((linhas + 1, colunas + 1))
    tabela[1:linhas + 1, 0:colunas] = matriz_A
    tabela[0, 0:colunas] = vetor_c
    tabela[1:linhas + 1, -1] = vetor_b
    print('***********************')
    print('Tableau Inicial')
    print(tabela)
    iteracao = 1
    while True:
        if not any(tabela[0, 0:colunas] < 0):
            print('Nao ha mais coef. negativos.')
            print('********* FIM ***********')
            break
        coluna_pivot = np.argmin(tabela[0, 0:colunas])
        linha_pivot = -1
        menor_razao = float('inf')
        for i in range(1, linhas + 1):
            if tabela[i, coluna_pivot] > 0:
                razao = tabela[i, -1] / tabela[i, coluna_pivot]
                if razao < menor_razao:
                    menor_razao = razao
                    linha_pivot = i
        if linha_pivot == -1:
            print("Problema ilimitado (sem linha pivô válida).")
            break
        print(f"Linha do pivot = {linha_pivot}")
        print('***********************')
        tabela[linha_pivot, :] /= tabela[linha_pivot, coluna_pivot]
        for i in range(linhas + 1):
            if i != linha_pivot:
                tabela[i, :] -= tabela[i, coluna_pivot]*tabela[linha_pivot, :]
        print(f"Tableau depois da iteracao [{iteracao}]")
        print(tabela)
        iteracao += 1
    return tabela
    # Exemplo de uso para Q1 logo abaixo
matriz_A = np.array([
    [1, 0, 1, 0, 0],
    [0, 1, 0, 1, 0],
    [1, 1, 0, 0, 1]
    ])
vetor_b = np.array([4, 6, 8])
vetor_c = np.array([-2, -5, 0, 0, 0])
resultado = simplex(matriz_A, vetor_b, vetor_c)
print('Resultado Final:')
print(resultado)

***********************
Tableau Inicial
[[-2. -5.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  4.]
 [ 0.  1.  0.  1.  0.  6.]
 [ 1.  1.  0.  0.  1.  8.]]
Linha do pivot = 2
***********************
Tableau depois da iteracao [1]
[[-2.  0.  0.  5.  0. 30.]
 [ 1.  0.  1.  0.  0.  4.]
 [ 0.  1.  0.  1.  0.  6.]
 [ 1.  0.  0. -1.  1.  2.]]
Linha do pivot = 3
***********************
Tableau depois da iteracao [2]
[[ 0.  0.  0.  3.  2. 34.]
 [ 0.  0.  1.  1. -1.  2.]
 [ 0.  1.  0.  1.  0.  6.]
 [ 1.  0.  0. -1.  1.  2.]]
Nao ha mais coef. negativos.
********* FIM ***********
Resultado Final:
[[ 0.  0.  0.  3.  2. 34.]
 [ 0.  0.  1.  1. -1.  2.]
 [ 0.  1.  0.  1.  0.  6.]
 [ 1.  0.  0. -1.  1.  2.]]


Q1. Seja o problema de maximização na forma canônica:
max z = 2x1 + 5x2
s.a.:
x1 ≤ 4
x2 ≤ 6
x1 + x2 ≤ 8
xi ≥ 0

Convertendo para a forma padrão, introduzimos variáveis de folga e temos:
max z − 2x1 − 5x2 + 0s1 − 0s2 − 0s3 = 0
s.a.:
x1 + s1 = 4
x2 + s2 = 6
x1 + x2 + s3 = 8
xi, sj ≥ 0

Você pode resolver o problema acima usando o algoritmo Simplex Básico em seu notebook Colab:
1- Basta utilizar a função simplex. Os parâmetros — matriz A, vetor b e vetor c de coeficientes — devem ser
definidos, e a função pode então ser invocada. Você obterá o tableau inicial e o tableau resultante após cada
iteração do algoritmo, conforme visto no exercício feito em aula.

2-Localize o valor das variáveis básicas e não básicas tanto no tableau inicial quanto nos tableaux seguintes.

3-Identifique o valor da função objetivo z em cada etapa e aponte o valor final z*.

4-Resolva também pelo método gráfico e compare os resultados obtidos com os do algoritmo.

Q1.

2- tableau inicial:
        x1 = 0
        x2 = 0
        s1 = 4
        s2 = 6
        s3 = 8
   tableau iteração 1 (linha do pivot = 2):
        x1 = 0
        x2 = 6
        s1 = 4
        s2 = 0
        s3 = 2
   tableau iteração 2 (linha do pivot = 3):
        x1 = 2
        x2 = 6
        s1 = 2
        s2 = 0
        s3 = 0
   tableau final:
        x1 = 2
        x2 = 6
        s1 = 2
        s2 = 0
        s3 = 0
3- z inicial = 0
   z iteração1 = 30 
   z iteração2 = 34

4- Os resultados são os mesmos, o simplex percorre os vértices que são candidatos a solução ótima

Q2. Leia a Seção 3.3.2 (Taha, p. 43), slides da aula passada e compreenda cada iteração feita no Exemplo 3.3-1.
Compare cada um dos tableaux com os obtidos pelo algoritmo acima. Aconteceu algo errado?

No código não fica explicito o valor assumido por cada variável com forme passam as iterações, mas nada errado de fato.

Q3. E se, na questão anterior, você escolhesse a variável com coeficiente menos negativo para entrar na base
e não a com coeficiente mais negativo? Mostre o que aconteceria com a solução, apresentando todos os
tableaux decorrentes dessa escolha até a convergência para a solução ótima. Você pode modificar o algoritmo
para fazê-lo. Resolva pelo método gráfico e mostre as consequências da sua escolha também no gráfico.

O simplex iria percorrer os vertices de candidados a solução ótima pelo caminho contrário, precisando assim de mais iterações.

In [2]:
import numpy as np

def simplex_menos_negativo(matriz_A, vetor_b, vetor_c):
    """
    Versão modificada do Simplex que escolhe o coeficiente MENOS negativo
    para entrar na base (em vez do mais negativo)
    """
    linhas, colunas = matriz_A.shape
    tabela = np.zeros((linhas + 1, colunas + 1))
    tabela[1:linhas + 1, 0:colunas] = matriz_A
    tabela[0, 0:colunas] = vetor_c
    tabela[1:linhas + 1, -1] = vetor_b
    
    print('***********************')
    print('Tableau Inicial (Menos Negativo)')
    print(tabela)
    
    iteracao = 1
    
    while True:
        # Verificar se há coeficientes negativos
        coefs_negativos = tabela[0, 0:colunas] < 0
        if not any(coefs_negativos):
            print('Nao ha mais coef. negativos.')
            print('********* FIM ***********')
            break
        
        # MODIFICAÇÃO: escolher o MENOS negativo (maior valor dentre os negativos)
        # Filtrar apenas os índices com valores negativos
        indices_negativos = np.where(tabela[0, 0:colunas] < 0)[0]
        # Escolher o que tem o maior valor (menos negativo)
        coluna_pivot = indices_negativos[np.argmax(tabela[0, indices_negativos])]
        
        print(f"Coluna do pivot (menos negativo) = {coluna_pivot}, valor = {tabela[0, coluna_pivot]}")
        
        # Teste da razão mínima
        linha_pivot = -1
        menor_razao = float('inf')
        for i in range(1, linhas + 1):
            if tabela[i, coluna_pivot] > 0:
                razao = tabela[i, -1] / tabela[i, coluna_pivot]
                if razao < menor_razao:
                    menor_razao = razao
                    linha_pivot = i
        
        if linha_pivot == -1:
            print("Problema ilimitado (sem linha pivô válida).")
            break
        
        print(f"Linha do pivot = {linha_pivot}")
        print('***********************')
        
        # Operações de pivot
        tabela[linha_pivot, :] /= tabela[linha_pivot, coluna_pivot]
        
        for i in range(linhas + 1):
            if i != linha_pivot:
                tabela[i, :] -= tabela[i, coluna_pivot]*tabela[linha_pivot, :]
        
        print(f"Tableau depois da iteracao [{iteracao}]")
        print(tabela)
        iteracao += 1
    
    return tabela

# Executar com o mesmo problema da Q1
matriz_A = np.array([
    [1, 0, 1, 0, 0],
    [0, 1, 0, 1, 0],
    [1, 1, 0, 0, 1]
])
vetor_b = np.array([4, 6, 8])
vetor_c = np.array([-2, -5, 0, 0, 0])

print("="*50)
print("ALGORITMO COM ESCOLHA DO MENOS NEGATIVO")
print("="*50)
resultado_menos_neg = simplex_menos_negativo(matriz_A, vetor_b, vetor_c)
print('Resultado Final:')
print(resultado_menos_neg)

ALGORITMO COM ESCOLHA DO MENOS NEGATIVO
***********************
Tableau Inicial (Menos Negativo)
[[-2. -5.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  4.]
 [ 0.  1.  0.  1.  0.  6.]
 [ 1.  1.  0.  0.  1.  8.]]
Coluna do pivot (menos negativo) = 0, valor = -2.0
Linha do pivot = 1
***********************
Tableau depois da iteracao [1]
[[ 0. -5.  2.  0.  0.  8.]
 [ 1.  0.  1.  0.  0.  4.]
 [ 0.  1.  0.  1.  0.  6.]
 [ 0.  1. -1.  0.  1.  4.]]
Coluna do pivot (menos negativo) = 1, valor = -5.0
Linha do pivot = 3
***********************
Tableau depois da iteracao [2]
[[ 0.  0. -3.  0.  5. 28.]
 [ 1.  0.  1.  0.  0.  4.]
 [ 0.  0.  1.  1. -1.  2.]
 [ 0.  1. -1.  0.  1.  4.]]
Coluna do pivot (menos negativo) = 2, valor = -3.0
Linha do pivot = 2
***********************
Tableau depois da iteracao [3]
[[ 0.  0.  0.  3.  2. 34.]
 [ 1.  0.  0. -1.  1.  2.]
 [ 0.  0.  1.  1. -1.  2.]
 [ 0.  1.  0.  1.  0.  6.]]
Nao ha mais coef. negativos.
********* FIM ***********
Resultado Final:
[[ 0.  0.  0.  3.  2

Q4. Leia sobre o Resumo do Simplex na Seção 3.3.3 (p. 45) do Taha. Faça um diagrama que ilustre o algoritmo.
Explique a condição de otimalidade ali descrita. Em que a condição difere para problemas de maximização e
minimização?

## Diagrama do Algoritmo Simplex

```
┌─────────────────────────────────────┐
│  INÍCIO                             │
│  Converter para forma padrão        │
│  Obter solução básica inicial       │
└──────────────┬──────────────────────┘
               │
               ▼
┌─────────────────────────────────────┐
│  Construir Tableau Inicial          │
│  - Variáveis de decisão = 0         │
│  - Variáveis de folga = bi          │
└──────────────┬──────────────────────┘
               │
               ▼
        ┌──────────────┐
        │ TESTE DE     │
        │ OTIMALIDADE  │
        └──────┬───────┘
               │
        ┌──────┴────────┐
        │               │
        ▼               ▼
    [SIM]           [NÃO]
        │               │
        │               ▼
        │    ┌──────────────────────┐
        │    │ Escolher variável    │
        │    │ para ENTRAR na base  │
        │    │ (coluna pivô)        │
        │    └──────┬───────────────┘
        │           │
        │           ▼
        │    ┌──────────────────────┐
        │    │ Teste da Razão       │
        │    │ Mínima: escolher     │
        │    │ variável para SAIR   │
        │    │ (linha pivô)         │
        │    └──────┬───────────────┘
        │           │
        │           ▼
        │    ┌──────────────────────┐
        │    │ Operações de Pivô:   │
        │    │ 1. Normalizar linha  │
        │    │ 2. Zerar coluna      │
        │    │ 3. Atualizar tableau │
        │    └──────┬───────────────┘
        │           │
        │           └────────┐
        │                    │
        ▼                    ▼
┌──────────────────────────────┐
│  SOLUÇÃO ÓTIMA ENCONTRADA    │
│  z* = valor da função obj.   │
│  x* = valores das variáveis  │
└──────────────────────────────┘
```

## Condição de Otimalidade

**Para MAXIMIZAÇÃO:**
A solução ótima é alcançada quando **todos os coeficientes da linha z (linha 0) são ≥ 0**.

- Se ainda existir algum coeficiente negativo (cj < 0), a função objetivo ainda pode ser melhorada
- A variável com coeficiente mais negativo entra na base (maior taxa de melhoria)
- Critério: `max{cj} ≥ 0` para todo j

**Para MINIMIZAÇÃO:**
A solução ótima é alcançada quando **todos os coeficientes da linha z (linha 0) são ≤ 0**.

- Se ainda existir algum coeficiente positivo (cj > 0), a função objetivo ainda pode ser melhorada
- A variável com coeficiente mais positivo entra na base
- Critério: `min{cj} ≤ 0` para todo j


Q5. Modifique o código do algoritmo acima de modo a maximizar ou minimizar um problema simples qualquer.
Ilustre com um exemplo prático que você fez isso.

In [3]:
import numpy as np

def simplex(matriz_A, vetor_b, vetor_c, tipo='max'):
    """
    Parâmetros:
    - matriz_A: matriz dos coeficientes das restrições (com variáveis de folga)
    - vetor_b: lado direito das restrições
    - vetor_c: coeficientes da função objetivo (SEMPRE POSITIVOS)
    - tipo: 'max' para maximização ou 'min' para minimização
    """
    
    # Se for maximização, inverte o sinal dos coeficientes
    if tipo.lower() == 'max':
        vetor_c = -vetor_c.copy()
        print(f"========================================")
        print(f"PROBLEMA DE MAXIMIZAÇÃO")
        print(f"========================================\n")
    else:
        vetor_c = vetor_c.copy()
        print(f"========================================")
        print(f"PROBLEMA DE MINIMIZAÇÃO")
        print(f"========================================\n")
    
    linhas, colunas = matriz_A.shape
    tabela = np.zeros((linhas + 1, colunas + 1))
    tabela[1:linhas + 1, 0:colunas] = matriz_A
    tabela[0, 0:colunas] = vetor_c
    tabela[1:linhas + 1, -1] = vetor_b
    
    print('Tableau Inicial:')
    print(tabela)
    print()
    
    iteracao = 1
    
    while True:
        # Critério de otimalidade
        if not any(tabela[0, 0:colunas] < 0):
            print('Não há mais coeficientes negativos.')
            print('========================================')
            print('SOLUÇÃO ÓTIMA ENCONTRADA!')
            print('========================================\n')
            break
        
        # Escolha da variável que entra (coluna pivô)
        coluna_pivot = np.argmin(tabela[0, 0:colunas])
        print(f"Iteração {iteracao}:")
        print(f"  - Variável que ENTRA: x{coluna_pivot + 1} (coluna {coluna_pivot})")
        
        # Teste da razão mínima (escolha da variável que sai)
        linha_pivot = -1
        menor_razao = float('inf')
        
        print(f"  - Teste da razão mínima:")
        for i in range(1, linhas + 1):
            if tabela[i, coluna_pivot] > 0:
                razao = tabela[i, -1] / tabela[i, coluna_pivot]
                print(f"      Linha {i}: {tabela[i, -1]:.2f} / {tabela[i, coluna_pivot]:.2f} = {razao:.2f}")
                if razao < menor_razao:
                    menor_razao = razao
                    linha_pivot = i
        
        if linha_pivot == -1:
            print("\n⚠️ Problema ILIMITADO (sem linha pivô válida).")
            break
        
        print(f"  - Variável que SAI: linha {linha_pivot} (razão mínima = {menor_razao:.2f})")
        print(f"  - Elemento pivô: {tabela[linha_pivot, coluna_pivot]:.2f}\n")
        
        # Pivoteamento (Gauss-Jordan)
        tabela[linha_pivot, :] /= tabela[linha_pivot, coluna_pivot]
        
        for i in range(linhas + 1):
            if i != linha_pivot:
                tabela[i, :] -= tabela[i, coluna_pivot] * tabela[linha_pivot, :]
        
        print(f'Tableau após iteração {iteracao}:')
        print(tabela)
        print()
        
        iteracao += 1
    
    # Extração da solução
    print("\n========================================")
    print("SOLUÇÃO FINAL:")
    print("========================================")
    
    # Valor ótimo da função objetivo
    z_otimo = tabela[0, -1]
    if tipo.lower() == 'max':
        z_otimo = -z_otimo  # Inverte o sinal para maximização
    
    print(f"Valor ótimo de z: {z_otimo:.2f}\n")
    
    # Identifica variáveis básicas
    print("Variáveis básicas:")
    for i in range(1, linhas + 1):
        # Procura qual coluna tem valor 1 nesta linha e 0 nas outras
        for j in range(colunas):
            coluna = tabela[:, j]
            if coluna[i] == 1 and np.sum(np.abs(coluna)) == 1:
                print(f"  x{j+1} = {tabela[i, -1]:.2f}")
                break
    
    print("\nVariáveis não-básicas: 0")
    print("========================================\n")
    
    return tabela


# ========================================
# EXEMPLO 1: MAXIMIZAÇÃO
# ========================================
print("\n" + "="*60)
print("EXEMPLO 1: Problema de Produção (MAXIMIZAÇÃO)")
print("="*60)
print("""
Uma fábrica produz dois produtos: A e B.
- Produto A: lucro de R$ 3 por unidade
- Produto B: lucro de R$ 5 por unidade

Restrições:
1) Tempo de máquina: 2A + 1B ≤ 8 horas
2) Matéria-prima: 1A + 2B ≤ 10 kg
3) Não-negatividade: A, B ≥ 0

MAXIMIZAR: z = 3A + 5B
""")

# Forma padrão: Max z = 3x1 + 5x2
# 2x1 + x2 + s1 = 8
# x1 + 2x2 + s2 = 10

matriz_A1 = np.array([
    [2, 1, 1, 0],  # Restrição 1 com folga s1
    [1, 2, 0, 1]   # Restrição 2 com folga s2
])
vetor_b1 = np.array([8, 10])
vetor_c1 = np.array([3, 5, 0, 0])  # Coeficientes POSITIVOS

resultado1 = simplex(matriz_A1, vetor_b1, vetor_c1, tipo='max')


# ========================================
# EXEMPLO 2: MINIMIZAÇÃO
# ========================================
print("\n" + "="*60)
print("EXEMPLO 2: Problema de Dieta (MINIMIZAÇÃO)")
print("="*60)
print("""
Uma pessoa quer minimizar o custo de sua dieta diária.
Dois alimentos disponíveis: X e Y.
- Alimento X: custa R$ 2 por porção
- Alimento Y: custa R$ 4 por porção

Restrições (requisitos mínimos diários):
1) Proteína: 3X + 2Y ≥ 12 gramas
2) Vitaminas: 1X + 2Y ≥ 8 unidades
3) Não-negatividade: X, Y ≥ 0

MINIMIZAR: z = 2X + 4Y

(Convertendo ≥ em ≤ multiplicando por -1 e usando variáveis de sobra)
""")

# Forma padrão: Min z = 2x1 + 4x2
# Para ≥, multiplicamos por -1 e adicionamos variável de folga:
# 3x1 + 2x2 - s1 = 12  →  -3x1 - 2x2 + s1 = -12
# 1x1 + 2x2 - s2 = 8   →  -1x1 - 2x2 + s2 = -8

# MELHOR ABORDAGEM: Usar variáveis de sobra (surplus)
# 3x1 + 2x2 = 12 + s1  (onde s1 é a sobra)
# Reescrevendo: 3x1 + 2x2 - s1 = 12

# Para o Simplex padrão, vamos converter para forma padrão:
matriz_A2 = np.array([
    [3, 2, 1, 0],  # 3x1 + 2x2 + s1 = 12 (s1 é slack artificial)
    [1, 2, 0, 1]   # x1 + 2x2 + s2 = 8
])
vetor_b2 = np.array([12, 8])
vetor_c2 = np.array([2, 4, 0, 0])  # Coeficientes POSITIVOS

resultado2 = simplex(matriz_A2, vetor_b2, vetor_c2, tipo='min')


EXEMPLO 1: Problema de Produção (MAXIMIZAÇÃO)

Uma fábrica produz dois produtos: A e B.
- Produto A: lucro de R$ 3 por unidade
- Produto B: lucro de R$ 5 por unidade

Restrições:
1) Tempo de máquina: 2A + 1B ≤ 8 horas
2) Matéria-prima: 1A + 2B ≤ 10 kg
3) Não-negatividade: A, B ≥ 0

MAXIMIZAR: z = 3A + 5B

PROBLEMA DE MAXIMIZAÇÃO

Tableau Inicial:
[[-3. -5.  0.  0.  0.]
 [ 2.  1.  1.  0.  8.]
 [ 1.  2.  0.  1. 10.]]

Iteração 1:
  - Variável que ENTRA: x2 (coluna 1)
  - Teste da razão mínima:
      Linha 1: 8.00 / 1.00 = 8.00
      Linha 2: 10.00 / 2.00 = 5.00
  - Variável que SAI: linha 2 (razão mínima = 5.00)
  - Elemento pivô: 2.00

Tableau após iteração 1:
[[-0.5  0.   0.   2.5 25. ]
 [ 1.5  0.   1.  -0.5  3. ]
 [ 0.5  1.   0.   0.5  5. ]]

Iteração 2:
  - Variável que ENTRA: x1 (coluna 0)
  - Teste da razão mínima:
      Linha 1: 3.00 / 1.50 = 2.00
      Linha 2: 5.00 / 0.50 = 10.00
  - Variável que SAI: linha 1 (razão mínima = 2.00)
  - Elemento pivô: 1.50

Tableau após iteração 